[program:queue-worker]
; Run webhooks and notification mails in the background, restart every hour to free memory
command=php /var/www/html/artisan queue:work --sleep=3 --max-time=3600
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
